If Not Exists (
	select *
	from sys.columns
	where object_id = Object_Id(N'dbo.RawDroolMetric')
	and name = 'overall_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area'
)
Alter table dbo.RawDroolMetric
	add [overall_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area] float null

If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add overall_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add overall_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'overall_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add overall_pct_diff_12mo_turf_rebate_area_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add reshoa_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add reshoa_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'reshoa_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add reshoa_pct_diff_12mo_turf_rebate_area_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add res_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add res_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'res_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add res_pct_diff_12mo_turf_rebate_area_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add com_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add com_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'com_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add com_pct_diff_12mo_turf_rebate_area_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add city_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add city_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'city_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add city_pct_diff_12mo_turf_rebate_area_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_sprinkler_nozzles_rebate_sum') Alter table dbo.RawDroolMetric Add hoa_sprinkler_nozzles_rebate_sum float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_daily_outdoor_budget_per_irrig_area') Alter table dbo.RawDroolMetric Add hoa_daily_outdoor_budget_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_meter_over_total_budget_fraction') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_meter_over_total_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_meter_budget_overage_per_meter') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_meter_budget_overage_per_meter float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_meter_over_est_outdoor_budget_fraction') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_meter_over_est_outdoor_budget_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_meter_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_meter_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_meter_est_outdoor_usage_per_capita_mean float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_meter_budget_overage_fraction_total') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_meter_budget_overage_fraction_total float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_est_outdoor_usage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_est_outdoor_budget_overage_per_irrig_area float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_daily_est_outdoor_budget_overage_fraction_outdoor_budget float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_rebate_participation_fraction') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_rebate_participation_fraction float null;
If not exists (select * from sys.columns where object_id = Object_ID(N'dbo.RawDroolMetric') and name = 'hoa_pct_diff_12mo_turf_rebate_area_fraction') Alter table dbo.RawDroolMetric Add hoa_pct_diff_12mo_turf_rebate_area_fraction float null;