version: '3.7'

services:
  drooltool.api:
    image: drooltool/api
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    ports:
      - "7890:80"
      - "7889:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
    volumes:
      - ~/.aspnet/https:/https:ro