version: '3.7'

services:
  drooltool.api:
    build:
      dockerfile: DroolTool.API/LocalDockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - KEYSTONE_HOST_OLD=${KEYSTONE_HOST_OLD}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - DROOLTOOL_WEB_URL=${DROOLTOOL_WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - MetricsDatabaseFTPUrl=${MetricsDatabaseFTPUrl}
      - NeighborhoodSourceCoordinateSystemID=${NeighborhoodSourceCoordinateSystemID}
      - HangfireUserName=${HangfireUserName}
      - HangfirePassword=${HangfirePassword}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_VERIFY_URL=${RECAPTCHA_VERIFY_URL}
      - RECAPTCHA_SCORE_THRESHOLD=${RECAPTCHA_SCORE_THRESHOLD}