version: '3.7'

services:
  drooltool.api:
    image: drooltool/api
    build:
      args:
        source: .
    ports:
      - "7890:8080"
      - "7889:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - DROOLTOOL_WEB_URL=${DROOLTOOL_WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - MetricsDatabaseFTPUrl=${MetricsDatabaseFTPUrl}
      - NeighborhoodSourceCoordinateSystemID=${NeighborhoodSourceCoordinateSystemID}
      - HangfireUserName=${HangfireUserName}
      - HangfirePassword=${HangfirePassword}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_VERIFY_URL=${RECAPTCHA_VERIFY_URL}
      - RECAPTCHA_SCORE_THRESHOLD=${RECAPTCHA_SCORE_THRESHOLD}

    volumes:
      - ~/.aspnet/https:/https:ro

  geoserver:
    container_name: drooltool_geoserver
    image: kartoza/geoserver:2.25.2
    environment:
      - ENABLE_JSONP=true
      - CATALINA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
      - ENV_PROPERTIES=/opt/geoserver/geoserver-environment.properties
      - STABLE_EXTENSIONS=sqlserver-plugin
      - TOMCAT_EXTRAS=false
      - ROOT_WEBAPP_REDIRECT=true
      - SAMPLE_DATA=false
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=${GeoserverAdminPassword}
    ports:
      - 127.0.0.1:7825:8080
    volumes:
      - c:/git/sitkatech/drooltool/DroolTool.GeoServer/data_dir:/opt/geoserver/data_dir
      - c:/sitka/DroolTool/GeoServer/geoserver-environment.properties:/opt/geoserver/geoserver-environment.properties
