{{ if eq .Values.global.env.name "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/drooltoolApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Production"
  SITKA_EMAIL_REDIRECT: ""
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  PlatformLongName: "Orange County Urban Drool Tool"
  PlatformShortName: "Urban Drool Tool"
  LeadOrganizationShortName: "OC"
  LeadOrganizationHomeUrl: "https://orangecounty.gov/"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  KEYSTONE_HOST: "https://identity.sitkatech.com"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
  MapquestApiUrlWithNominatimApiKey: ""
{{ end }}