services:
    drooltool.web:
        image: drooltool/web
        build:
            args:
                env: ${ENVIRONMENT}
            context: ../..
            dockerfile: DroolTool.Web/Dockerfile
